---
- name: Install Tomcat on Centos
  hosts: g1
  become: yes
  tasks:
    - name: Update the system
      yum:
        name: "*"
        state: latest
    - name: Install Java
      yum:
        name: java-1.8.0-openjdk
        state: present
     - name: Create a Directory /opt/tomcat8
      become: yes
      file:
        path: /opt/tomcat9
        state: directory
        mode: 755
        owner: tomcat
        group: tomcat    
    - name: Download Tomcat
      get_url:
        url: http://www-us.apache.org/dist/tomcat/tomcat-9/v9.0.31/bin/apache-tomcat-9.0.31.tar.gz
        dest: /opt/tomvat9/tomcat.tar.gz
    - name: Extract Tomcat
      unarchive:
        src: /opt/tomcat9/tomcat.tar.gz
        dest: /opt/
    - name: Create Tomcat symlink
      file:
        src: /opt/apache-tomcat-9.0.31
        dest: /opt/tomcat
        state: link
    - name: Add Tomcat to Environment Variables
      lineinfile:
        dest: /etc/environment
        line: CATALINA_HOME=/opt/tomcat
        state: present
        insertafter: EOL
    - name: null
      file:
        src: /opt/apache-tomcat-9.0.31
        dest: /opt/tomcat
        state: link
- name: Deploy Time Display Script
  hosts: tomcat
  become: yes
  tasks:
    - name: Copy script to servers
      copy:
        src: /path/to/currenttime.sh
        dest: /usr/local/bin/
        mode: 755
    - name: Make script executable
      file:
        path: /usr/local/bin/currenttime.sh
        mode: 755
- name: Schedule time display script
  hosts: tomcat
  become: yes
  tasks:
    - name: Create cron job
      cron:
        name: Display current time
        job: /usr/local/bin/currenttime.sh
        minute: "*/2"
...
